apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: team-pegasus-web-pipeline-run-
spec:
  serviceAccountNames: 
  - serviceAccountName: build-bot
    taskName: build-image
  pipelineRef:
    name: team-pegasus-web-pipeline
  workspaces:
    - name: pipeline-shared-data
      persistentVolumeClaim:
        claimName: team-pegasus-pvc