apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: api-pipeline-run-
spec:
  serviceAccountNames:
    - serviceAccountName: build-bot
      taskName: build-image
  pipelineRef:
    name: api-pipeline
  workspaces:
    - name: pipeline-shared-data
      persistentVolumeClaim:
        claimName: team-pegasus-api-pvc2